# Generated by Django 4.2.3 on 2025-07-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_usersubscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
